name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push the Docker image
      run: |
        TAG=$(date +%s)
        docker build ./frontend --file ./frontend/Dockerfile --tag germancruzpallares/temperaturas-frontend:$TAG
        docker push germancruzpallares/temperaturas-frontend:$TAG
        echo "NEW_TAG=$TAG" >> $GITHUB_ENV

    - name: Update Kubernetes manifests
      run: |
        sed -i "s|image: germancruzpallares/temperaturas-frontend:.*|image: germancruzpallares/temperaturas-frontend:${{ env.NEW_TAG }}|g" frontend-k8s.yaml
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add frontend-k8s.yaml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update frontend image tag to ${{ env.NEW_TAG }}" && git push origin main)